"""empty message

Revision ID: 5871e186a7b1
Revises: 
Create Date: 2020-01-28 12:38:09.692441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5871e186a7b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='drivers_pkey')
                    )
    op.create_table('vehicles',
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column('make', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='vehicles_pkey')
                    )

    op.create_table('todobs',
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
                   sa.PrimaryKeyConstraint('id', name='todos_pkey')
                    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('drivers')
    op.drop_table('todos')


    # ### end Alembic commands ###
