"""empty message

Revision ID: 75f52145af3d
Revises: 81c817623a81
Create Date: 2020-01-30 19:38:21.604464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f52145af3d'
down_revision = '81c817623a81'
branch_labels = None
depends_on = None


def upgrade():
    #at the beg. set list_id nullable = true here and in app.py
    #run this in psql
    # insert into todolists (name)  values ('uncategorized' );

    #todoapp=# update todos set list_id =1 where list_id is null;

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
