"""empty message

Revision ID: 963ef5e18f47
Revises: 75f52145af3d
Create Date: 2020-01-30 19:52:21.414721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963ef5e18f47'
down_revision = '75f52145af3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
